import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Inter, JetBrains_Mono } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

import "./globals.css";

const sansFont = Inter({ subsets: ["latin"], variable: "--font-sans" });

const monoFont = JetBrains_Mono({
    variable: "--font-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn(
                "h-full",
                "antialiased",
                sansFont.variable,
                monoFont.variable,
                "font-sans",
            )}
            suppressHydrationWarning
        >
            <body className="flex h-screen flex-col">
                <ThemeProvider
                    attribute="class"
                    enableSystem
                    disableTransitionOnChange
                    enableColorScheme
                >
                    <TooltipProvider>
                        {children}

                        <Toaster />
                    </TooltipProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
